/* Generated by makeenums.pl */

static const GEnumValue _gimp_add_mask_type_values[] = {
  { GIMP_ADD_WHITE_MASK, "GIMP_ADD_WHITE_MASK", "white-mask" },
  { GIMP_ADD_BLACK_MASK, "GIMP_ADD_BLACK_MASK", "black-mask" },
  { GIMP_ADD_ALPHA_MASK, "GIMP_ADD_ALPHA_MASK", "alpha-mask" },
  { GIMP_ADD_SELECTION_MASK, "GIMP_ADD_SELECTION_MASK", "selection-mask" },
  { GIMP_ADD_COPY_MASK, "GIMP_ADD_COPY_MASK", "copy-mask" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_blend_mode_values[] = {
  { GIMP_FG_BG_RGB_MODE, "GIMP_FG_BG_RGB_MODE", "fg-bg-rgb-mode" },
  { GIMP_FG_BG_HSV_MODE, "GIMP_FG_BG_HSV_MODE", "fg-bg-hsv-mode" },
  { GIMP_FG_TRANSPARENT_MODE, "GIMP_FG_TRANSPARENT_MODE", "fg-transparent-mode" },
  { GIMP_CUSTOM_MODE, "GIMP_CUSTOM_MODE", "custom-mode" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_brush_application_mode_values[] = {
  { GIMP_BRUSH_HARD, "GIMP_BRUSH_HARD", "hard" },
  { GIMP_BRUSH_SOFT, "GIMP_BRUSH_SOFT", "soft" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_bucket_fill_mode_values[] = {
  { GIMP_FG_BUCKET_FILL, "GIMP_FG_BUCKET_FILL", "fg-bucket-fill" },
  { GIMP_BG_BUCKET_FILL, "GIMP_BG_BUCKET_FILL", "bg-bucket-fill" },
  { GIMP_PATTERN_BUCKET_FILL, "GIMP_PATTERN_BUCKET_FILL", "pattern-bucket-fill" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_channel_lut_type_values[] = {
  { GIMP_VALUE_LUT, "GIMP_VALUE_LUT", "value-lut" },
  { GIMP_RED_LUT, "GIMP_RED_LUT", "red-lut" },
  { GIMP_GREEN_LUT, "GIMP_GREEN_LUT", "green-lut" },
  { GIMP_BLUE_LUT, "GIMP_BLUE_LUT", "blue-lut" },
  { GIMP_ALPHA_LUT, "GIMP_ALPHA_LUT", "alpha-lut" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_channel_ops_values[] = {
  { GIMP_CHANNEL_OP_ADD, "GIMP_CHANNEL_OP_ADD", "add" },
  { GIMP_CHANNEL_OP_SUBTRACT, "GIMP_CHANNEL_OP_SUBTRACT", "subtract" },
  { GIMP_CHANNEL_OP_REPLACE, "GIMP_CHANNEL_OP_REPLACE", "replace" },
  { GIMP_CHANNEL_OP_INTERSECT, "GIMP_CHANNEL_OP_INTERSECT", "intersect" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_channel_type_values[] = {
  { GIMP_RED_CHANNEL, "GIMP_RED_CHANNEL", "red-channel" },
  { GIMP_GREEN_CHANNEL, "GIMP_GREEN_CHANNEL", "green-channel" },
  { GIMP_BLUE_CHANNEL, "GIMP_BLUE_CHANNEL", "blue-channel" },
  { GIMP_GRAY_CHANNEL, "GIMP_GRAY_CHANNEL", "gray-channel" },
  { GIMP_INDEXED_CHANNEL, "GIMP_INDEXED_CHANNEL", "indexed-channel" },
  { GIMP_ALPHA_CHANNEL, "GIMP_ALPHA_CHANNEL", "alpha-channel" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_clone_type_values[] = {
  { GIMP_IMAGE_CLONE, "GIMP_IMAGE_CLONE", "image-clone" },
  { GIMP_PATTERN_CLONE, "GIMP_PATTERN_CLONE", "pattern-clone" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_convert_dither_type_values[] = {
  { GIMP_NO_DITHER, "GIMP_NO_DITHER", "no-dither" },
  { GIMP_FS_DITHER, "GIMP_FS_DITHER", "fs-dither" },
  { GIMP_FSLOWBLEED_DITHER, "GIMP_FSLOWBLEED_DITHER", "fslowbleed-dither" },
  { GIMP_FIXED_DITHER, "GIMP_FIXED_DITHER", "fixed-dither" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_convert_palette_type_values[] = {
  { GIMP_MAKE_PALETTE, "GIMP_MAKE_PALETTE", "make-palette" },
  { GIMP_REUSE_PALETTE, "GIMP_REUSE_PALETTE", "reuse-palette" },
  { GIMP_WEB_PALETTE, "GIMP_WEB_PALETTE", "web-palette" },
  { GIMP_MONO_PALETTE, "GIMP_MONO_PALETTE", "mono-palette" },
  { GIMP_CUSTOM_PALETTE, "GIMP_CUSTOM_PALETTE", "custom-palette" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_convolution_type_values[] = {
  { GIMP_NORMAL_CONVOL, "GIMP_NORMAL_CONVOL", "normal-convol" },
  { GIMP_ABSOLUTE_CONVOL, "GIMP_ABSOLUTE_CONVOL", "absolute-convol" },
  { GIMP_NEGATIVE_CONVOL, "GIMP_NEGATIVE_CONVOL", "negative-convol" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_convolve_type_values[] = {
  { GIMP_BLUR_CONVOLVE, "GIMP_BLUR_CONVOLVE", "blur-convolve" },
  { GIMP_SHARPEN_CONVOLVE, "GIMP_SHARPEN_CONVOLVE", "sharpen-convolve" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_dodge_burn_type_values[] = {
  { GIMP_DODGE, "GIMP_DODGE", "dodge" },
  { GIMP_BURN, "GIMP_BURN", "burn" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_fill_type_values[] = {
  { GIMP_FOREGROUND_FILL, "GIMP_FOREGROUND_FILL", "foreground-fill" },
  { GIMP_BACKGROUND_FILL, "GIMP_BACKGROUND_FILL", "background-fill" },
  { GIMP_WHITE_FILL, "GIMP_WHITE_FILL", "white-fill" },
  { GIMP_TRANSPARENT_FILL, "GIMP_TRANSPARENT_FILL", "transparent-fill" },
  { GIMP_NO_FILL, "GIMP_NO_FILL", "no-fill" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_gradient_paint_mode_values[] = {
  { GIMP_GRADIENT_ONCE_FORWARD, "GIMP_GRADIENT_ONCE_FORWARD", "once-forward" },
  { GIMP_GRADIENT_ONCE_BACKWARD, "GIMP_GRADIENT_ONCE_BACKWARD", "once-backward" },
  { GIMP_GRADIENT_LOOP_SAWTOOTH, "GIMP_GRADIENT_LOOP_SAWTOOTH", "loop-sawtooth" },
  { GIMP_GRADIENT_LOOP_TRIANGLE, "GIMP_GRADIENT_LOOP_TRIANGLE", "loop-triangle" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_gradient_type_values[] = {
  { GIMP_LINEAR, "GIMP_LINEAR", "linear" },
  { GIMP_BILINEAR, "GIMP_BILINEAR", "bilinear" },
  { GIMP_RADIAL, "GIMP_RADIAL", "radial" },
  { GIMP_SQUARE, "GIMP_SQUARE", "square" },
  { GIMP_CONICAL_SYMMETRIC, "GIMP_CONICAL_SYMMETRIC", "conical-symmetric" },
  { GIMP_CONICAL_ASYMMETRIC, "GIMP_CONICAL_ASYMMETRIC", "conical-asymmetric" },
  { GIMP_SHAPEBURST_ANGULAR, "GIMP_SHAPEBURST_ANGULAR", "shapeburst-angular" },
  { GIMP_SHAPEBURST_SPHERICAL, "GIMP_SHAPEBURST_SPHERICAL", "shapeburst-spherical" },
  { GIMP_SHAPEBURST_DIMPLED, "GIMP_SHAPEBURST_DIMPLED", "shapeburst-dimpled" },
  { GIMP_SPIRAL_CLOCKWISE, "GIMP_SPIRAL_CLOCKWISE", "spiral-clockwise" },
  { GIMP_SPIRAL_ANTICLOCKWISE, "GIMP_SPIRAL_ANTICLOCKWISE", "spiral-anticlockwise" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_hue_range_values[] = {
  { GIMP_ALL_HUES, "GIMP_ALL_HUES", "all-hues" },
  { GIMP_RED_HUES, "GIMP_RED_HUES", "red-hues" },
  { GIMP_YELLOW_HUES, "GIMP_YELLOW_HUES", "yellow-hues" },
  { GIMP_GREEN_HUES, "GIMP_GREEN_HUES", "green-hues" },
  { GIMP_CYAN_HUES, "GIMP_CYAN_HUES", "cyan-hues" },
  { GIMP_BLUE_HUES, "GIMP_BLUE_HUES", "blue-hues" },
  { GIMP_MAGENTA_HUES, "GIMP_MAGENTA_HUES", "magenta-hues" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_image_base_type_values[] = {
  { GIMP_RGB, "GIMP_RGB", "rgb" },
  { GIMP_GRAY, "GIMP_GRAY", "gray" },
  { GIMP_INDEXED, "GIMP_INDEXED", "indexed" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_image_type_values[] = {
  { GIMP_RGB_IMAGE, "GIMP_RGB_IMAGE", "rgb-image" },
  { GIMP_RGBA_IMAGE, "GIMP_RGBA_IMAGE", "rgba-image" },
  { GIMP_GRAY_IMAGE, "GIMP_GRAY_IMAGE", "gray-image" },
  { GIMP_GRAYA_IMAGE, "GIMP_GRAYA_IMAGE", "graya-image" },
  { GIMP_INDEXED_IMAGE, "GIMP_INDEXED_IMAGE", "indexed-image" },
  { GIMP_INDEXEDA_IMAGE, "GIMP_INDEXEDA_IMAGE", "indexeda-image" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_layer_mode_effects_values[] = {
  { GIMP_NORMAL_MODE, "GIMP_NORMAL_MODE", "normal-mode" },
  { GIMP_DISSOLVE_MODE, "GIMP_DISSOLVE_MODE", "dissolve-mode" },
  { GIMP_BEHIND_MODE, "GIMP_BEHIND_MODE", "behind-mode" },
  { GIMP_MULTIPLY_MODE, "GIMP_MULTIPLY_MODE", "multiply-mode" },
  { GIMP_SCREEN_MODE, "GIMP_SCREEN_MODE", "screen-mode" },
  { GIMP_OVERLAY_MODE, "GIMP_OVERLAY_MODE", "overlay-mode" },
  { GIMP_DIFFERENCE_MODE, "GIMP_DIFFERENCE_MODE", "difference-mode" },
  { GIMP_ADDITION_MODE, "GIMP_ADDITION_MODE", "addition-mode" },
  { GIMP_SUBTRACT_MODE, "GIMP_SUBTRACT_MODE", "subtract-mode" },
  { GIMP_DARKEN_ONLY_MODE, "GIMP_DARKEN_ONLY_MODE", "darken-only-mode" },
  { GIMP_LIGHTEN_ONLY_MODE, "GIMP_LIGHTEN_ONLY_MODE", "lighten-only-mode" },
  { GIMP_HUE_MODE, "GIMP_HUE_MODE", "hue-mode" },
  { GIMP_SATURATION_MODE, "GIMP_SATURATION_MODE", "saturation-mode" },
  { GIMP_COLOR_MODE, "GIMP_COLOR_MODE", "color-mode" },
  { GIMP_VALUE_MODE, "GIMP_VALUE_MODE", "value-mode" },
  { GIMP_DIVIDE_MODE, "GIMP_DIVIDE_MODE", "divide-mode" },
  { GIMP_DODGE_MODE, "GIMP_DODGE_MODE", "dodge-mode" },
  { GIMP_BURN_MODE, "GIMP_BURN_MODE", "burn-mode" },
  { GIMP_HARDLIGHT_MODE, "GIMP_HARDLIGHT_MODE", "hardlight-mode" },
  { GIMP_SOFTLIGHT_MODE, "GIMP_SOFTLIGHT_MODE", "softlight-mode" },
  { GIMP_GRAIN_EXTRACT_MODE, "GIMP_GRAIN_EXTRACT_MODE", "grain-extract-mode" },
  { GIMP_GRAIN_MERGE_MODE, "GIMP_GRAIN_MERGE_MODE", "grain-merge-mode" },
  { GIMP_COLOR_ERASE_MODE, "GIMP_COLOR_ERASE_MODE", "color-erase-mode" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_mask_apply_mode_values[] = {
  { GIMP_MASK_APPLY, "GIMP_MASK_APPLY", "apply" },
  { GIMP_MASK_DISCARD, "GIMP_MASK_DISCARD", "discard" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_merge_type_values[] = {
  { GIMP_EXPAND_AS_NECESSARY, "GIMP_EXPAND_AS_NECESSARY", "expand-as-necessary" },
  { GIMP_CLIP_TO_IMAGE, "GIMP_CLIP_TO_IMAGE", "clip-to-image" },
  { GIMP_CLIP_TO_BOTTOM_LAYER, "GIMP_CLIP_TO_BOTTOM_LAYER", "clip-to-bottom-layer" },
  { GIMP_FLATTEN_IMAGE, "GIMP_FLATTEN_IMAGE", "flatten-image" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_offset_type_values[] = {
  { GIMP_OFFSET_BACKGROUND, "GIMP_OFFSET_BACKGROUND", "background" },
  { GIMP_OFFSET_TRANSPARENT, "GIMP_OFFSET_TRANSPARENT", "transparent" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_orientation_type_values[] = {
  { GIMP_ORIENTATION_HORIZONTAL, "GIMP_ORIENTATION_HORIZONTAL", "horizontal" },
  { GIMP_ORIENTATION_VERTICAL, "GIMP_ORIENTATION_VERTICAL", "vertical" },
  { GIMP_ORIENTATION_UNKNOWN, "GIMP_ORIENTATION_UNKNOWN", "unknown" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_paint_application_mode_values[] = {
  { GIMP_PAINT_CONSTANT, "GIMP_PAINT_CONSTANT", "constant" },
  { GIMP_PAINT_INCREMENTAL, "GIMP_PAINT_INCREMENTAL", "incremental" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_repeat_mode_values[] = {
  { GIMP_REPEAT_NONE, "GIMP_REPEAT_NONE", "none" },
  { GIMP_REPEAT_SAWTOOTH, "GIMP_REPEAT_SAWTOOTH", "sawtooth" },
  { GIMP_REPEAT_TRIANGULAR, "GIMP_REPEAT_TRIANGULAR", "triangular" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_run_mode_values[] = {
  { GIMP_RUN_INTERACTIVE, "GIMP_RUN_INTERACTIVE", "interactive" },
  { GIMP_RUN_NONINTERACTIVE, "GIMP_RUN_NONINTERACTIVE", "noninteractive" },
  { GIMP_RUN_WITH_LAST_VALS, "GIMP_RUN_WITH_LAST_VALS", "with-last-vals" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_transfer_mode_values[] = {
  { GIMP_SHADOWS, "GIMP_SHADOWS", "shadows" },
  { GIMP_MIDTONES, "GIMP_MIDTONES", "midtones" },
  { GIMP_HIGHLIGHTS, "GIMP_HIGHLIGHTS", "highlights" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_size_type_values[] = {
  { GIMP_PIXELS, "GIMP_PIXELS", "pixels" },
  { GIMP_POINTS, "GIMP_POINTS", "points" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_unit_values[] = {
  { GIMP_UNIT_PIXEL, "GIMP_UNIT_PIXEL", "pixel" },
  { GIMP_UNIT_INCH, "GIMP_UNIT_INCH", "inch" },
  { GIMP_UNIT_MM, "GIMP_UNIT_MM", "mm" },
  { GIMP_UNIT_POINT, "GIMP_UNIT_POINT", "point" },
  { GIMP_UNIT_PICA, "GIMP_UNIT_PICA", "pica" },
  { GIMP_UNIT_END, "GIMP_UNIT_END", "end" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_pdb_arg_type_values[] = {
  { GIMP_PDB_INT32, "GIMP_PDB_INT32", "int32" },
  { GIMP_PDB_INT16, "GIMP_PDB_INT16", "int16" },
  { GIMP_PDB_INT8, "GIMP_PDB_INT8", "int8" },
  { GIMP_PDB_FLOAT, "GIMP_PDB_FLOAT", "float" },
  { GIMP_PDB_STRING, "GIMP_PDB_STRING", "string" },
  { GIMP_PDB_INT32ARRAY, "GIMP_PDB_INT32ARRAY", "int32array" },
  { GIMP_PDB_INT16ARRAY, "GIMP_PDB_INT16ARRAY", "int16array" },
  { GIMP_PDB_INT8ARRAY, "GIMP_PDB_INT8ARRAY", "int8array" },
  { GIMP_PDB_FLOATARRAY, "GIMP_PDB_FLOATARRAY", "floatarray" },
  { GIMP_PDB_STRINGARRAY, "GIMP_PDB_STRINGARRAY", "stringarray" },
  { GIMP_PDB_COLOR, "GIMP_PDB_COLOR", "color" },
  { GIMP_PDB_REGION, "GIMP_PDB_REGION", "region" },
  { GIMP_PDB_DISPLAY, "GIMP_PDB_DISPLAY", "display" },
  { GIMP_PDB_IMAGE, "GIMP_PDB_IMAGE", "image" },
  { GIMP_PDB_LAYER, "GIMP_PDB_LAYER", "layer" },
  { GIMP_PDB_CHANNEL, "GIMP_PDB_CHANNEL", "channel" },
  { GIMP_PDB_DRAWABLE, "GIMP_PDB_DRAWABLE", "drawable" },
  { GIMP_PDB_SELECTION, "GIMP_PDB_SELECTION", "selection" },
  { GIMP_PDB_BOUNDARY, "GIMP_PDB_BOUNDARY", "boundary" },
  { GIMP_PDB_PATH, "GIMP_PDB_PATH", "path" },
  { GIMP_PDB_PARASITE, "GIMP_PDB_PARASITE", "parasite" },
  { GIMP_PDB_STATUS, "GIMP_PDB_STATUS", "status" },
  { GIMP_PDB_END, "GIMP_PDB_END", "end" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_pdb_proc_type_values[] = {
  { GIMP_INTERNAL, "GIMP_INTERNAL", "internal" },
  { GIMP_PLUGIN, "GIMP_PLUGIN", "plugin" },
  { GIMP_EXTENSION, "GIMP_EXTENSION", "extension" },
  { GIMP_TEMPORARY, "GIMP_TEMPORARY", "temporary" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_pdb_status_type_values[] = {
  { GIMP_PDB_EXECUTION_ERROR, "GIMP_PDB_EXECUTION_ERROR", "execution-error" },
  { GIMP_PDB_CALLING_ERROR, "GIMP_PDB_CALLING_ERROR", "calling-error" },
  { GIMP_PDB_PASS_THROUGH, "GIMP_PDB_PASS_THROUGH", "pass-through" },
  { GIMP_PDB_SUCCESS, "GIMP_PDB_SUCCESS", "success" },
  { GIMP_PDB_CANCEL, "GIMP_PDB_CANCEL", "cancel" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_message_handler_type_values[] = {
  { GIMP_MESSAGE_BOX, "GIMP_MESSAGE_BOX", "message-box" },
  { GIMP_CONSOLE, "GIMP_CONSOLE", "console" },
  { GIMP_ERROR_CONSOLE, "GIMP_ERROR_CONSOLE", "error-console" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_stack_trace_mode_values[] = {
  { GIMP_STACK_TRACE_NEVER, "GIMP_STACK_TRACE_NEVER", "never" },
  { GIMP_STACK_TRACE_QUERY, "GIMP_STACK_TRACE_QUERY", "query" },
  { GIMP_STACK_TRACE_ALWAYS, "GIMP_STACK_TRACE_ALWAYS", "always" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_rgb_composite_mode_values[] = {
  { GIMP_RGB_COMPOSITE_NONE, "GIMP_RGB_COMPOSITE_NONE", "none" },
  { GIMP_RGB_COMPOSITE_NORMAL, "GIMP_RGB_COMPOSITE_NORMAL", "normal" },
  { GIMP_RGB_COMPOSITE_BEHIND, "GIMP_RGB_COMPOSITE_BEHIND", "behind" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_chain_position_values[] = {
  { GIMP_CHAIN_TOP, "GIMP_CHAIN_TOP", "top" },
  { GIMP_CHAIN_LEFT, "GIMP_CHAIN_LEFT", "left" },
  { GIMP_CHAIN_BOTTOM, "GIMP_CHAIN_BOTTOM", "bottom" },
  { GIMP_CHAIN_RIGHT, "GIMP_CHAIN_RIGHT", "right" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_color_area_type_values[] = {
  { GIMP_COLOR_AREA_FLAT, "GIMP_COLOR_AREA_FLAT", "flat" },
  { GIMP_COLOR_AREA_SMALL_CHECKS, "GIMP_COLOR_AREA_SMALL_CHECKS", "small-checks" },
  { GIMP_COLOR_AREA_LARGE_CHECKS, "GIMP_COLOR_AREA_LARGE_CHECKS", "large-checks" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_color_selector_channel_values[] = {
  { GIMP_COLOR_SELECTOR_HUE, "GIMP_COLOR_SELECTOR_HUE", "hue" },
  { GIMP_COLOR_SELECTOR_SATURATION, "GIMP_COLOR_SELECTOR_SATURATION", "saturation" },
  { GIMP_COLOR_SELECTOR_VALUE, "GIMP_COLOR_SELECTOR_VALUE", "value" },
  { GIMP_COLOR_SELECTOR_RED, "GIMP_COLOR_SELECTOR_RED", "red" },
  { GIMP_COLOR_SELECTOR_GREEN, "GIMP_COLOR_SELECTOR_GREEN", "green" },
  { GIMP_COLOR_SELECTOR_BLUE, "GIMP_COLOR_SELECTOR_BLUE", "blue" },
  { GIMP_COLOR_SELECTOR_ALPHA, "GIMP_COLOR_SELECTOR_ALPHA", "alpha" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_size_entry_update_policy_values[] = {
  { GIMP_SIZE_ENTRY_UPDATE_NONE, "GIMP_SIZE_ENTRY_UPDATE_NONE", "none" },
  { GIMP_SIZE_ENTRY_UPDATE_SIZE, "GIMP_SIZE_ENTRY_UPDATE_SIZE", "size" },
  { GIMP_SIZE_ENTRY_UPDATE_RESOLUTION, "GIMP_SIZE_ENTRY_UPDATE_RESOLUTION", "resolution" },
  { 0, NULL, NULL }
};
