/* Generated by makeenums.pl then MANUALLY EDITED!!! */

static const GEnumValue _gimp_unit_values[] = {
  { GIMP_UNIT_PIXEL, "GIMP_UNIT_PIXEL", "pixel" },
  { GIMP_UNIT_INCH, "GIMP_UNIT_INCH", "inch" },
  { GIMP_UNIT_MM, "GIMP_UNIT_MM", "mm" },
  { GIMP_UNIT_POINT, "GIMP_UNIT_POINT", "point" },
  { GIMP_UNIT_PICA, "GIMP_UNIT_PICA", "pica" },
  { GIMP_UNIT_END, "GIMP_UNIT_END", "end" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_chain_position_values[] = {
  { GIMP_CHAIN_TOP, "GIMP_CHAIN_TOP", "top" },
  { GIMP_CHAIN_LEFT, "GIMP_CHAIN_LEFT", "left" },
  { GIMP_CHAIN_BOTTOM, "GIMP_CHAIN_BOTTOM", "bottom" },
  { GIMP_CHAIN_RIGHT, "GIMP_CHAIN_RIGHT", "right" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_color_area_type_values[] = {
  { GIMP_COLOR_AREA_FLAT, "GIMP_COLOR_AREA_FLAT", "flat" },
  { GIMP_COLOR_AREA_SMALL_CHECKS, "GIMP_COLOR_AREA_SMALL_CHECKS", "small-checks" },
  { GIMP_COLOR_AREA_LARGE_CHECKS, "GIMP_COLOR_AREA_LARGE_CHECKS", "large-checks" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_color_selector_channel_values[] = {
  { GIMP_COLOR_SELECTOR_HUE, "GIMP_COLOR_SELECTOR_HUE", "hue" },
  { GIMP_COLOR_SELECTOR_SATURATION, "GIMP_COLOR_SELECTOR_SATURATION", "saturation" },
  { GIMP_COLOR_SELECTOR_VALUE, "GIMP_COLOR_SELECTOR_VALUE", "value" },
  { GIMP_COLOR_SELECTOR_RED, "GIMP_COLOR_SELECTOR_RED", "red" },
  { GIMP_COLOR_SELECTOR_GREEN, "GIMP_COLOR_SELECTOR_GREEN", "green" },
  { GIMP_COLOR_SELECTOR_BLUE, "GIMP_COLOR_SELECTOR_BLUE", "blue" },
  { GIMP_COLOR_SELECTOR_ALPHA, "GIMP_COLOR_SELECTOR_ALPHA", "alpha" },
  { 0, NULL, NULL }
};
static const GEnumValue _gimp_size_entry_update_policy_values[] = {
  { GIMP_SIZE_ENTRY_UPDATE_NONE, "GIMP_SIZE_ENTRY_UPDATE_NONE", "none" },
  { GIMP_SIZE_ENTRY_UPDATE_SIZE, "GIMP_SIZE_ENTRY_UPDATE_SIZE", "size" },
  { GIMP_SIZE_ENTRY_UPDATE_RESOLUTION, "GIMP_SIZE_ENTRY_UPDATE_RESOLUTION", "resolution" },
  { 0, NULL, NULL }
};

