#!/usr/local/bin/perl -w

use strict;
#BEGIN { $Gimp::verbose = 1; }
use Gimp qw(:auto __ N_);
use Gimp::Fu;
#Gimp::set_trace(TRACE_ALL);

&register(
  "test_dialogs", 'help', 'blurb', 'id', 'id', '20140411',
  N_ '<Toolbox>/Xtns/Perl/Test/Dialog', undef,
  [
    [ PF_COLOR, "colour", "Image colour", [255, 127, 0], ],
    [ PF_FONT, "font", "Font", 'Arial', ],
    [ PF_INT8, "int8", "Int8", 100],
    [ PF_INT16, "int16", "Int16", 100],
    [ PF_INT32, "int32", "Int32", 100],
    [ PF_FLOAT, "float", "FLOAT", 100],
  ],
  sub { }
);

exit main;
