#!/usr/bin/perl

use Gimp;

Gimp::on_lib {
   die "Not intended to be run from within GIMP!\n";
};

# on_net is called if connecting to an already open Perl-Server, or if
# spawning a gimp without an interface to run on.

Gimp::on_net {
  # simple benchmark ;)
  $img=new Gimp::Image(600,300,RGB);

# the is the same as $img = new Gimp::Image(600,300,RGB)
  $bg=$img->layer_new(30,20,RGB_IMAGE,"Background",100,NORMAL_MODE);
# you have to add a layer after you create it
  $bg->insert_layer(0,1);
# Show it (this slows things down)
  new Gimp::Display($img);

# do a bunch of operations just as a speed test, flushing in between
  Gimp::Context->push();
  for $i (0..255) {
     Gimp::Context->set_background([$i,255-$i,$i]);
     $bg->edit_fill(BACKGROUND_FILL);
     Gimp::Display->displays_flush();
  }
  Gimp::Context->pop();
#  Gimp::Net::server_quit;  # kill the gimp-perl-server-extension (ugly name)
};

exit main;
__END__

=head1 NAME

example-net - Demonstrate use of Gimp-Perl "net mode"

=head1 LICENSE

Copyright Marc Lehman.
Distributed under the same terms as Gimp-Perl.
