#!/usr/local/bin/perl -w

use strict;
use Gimp;
use Gimp::Fu;
#BEGIN { $Gimp::verbose = 1; }
#Gimp::set_trace(TRACE_ALL);

podregister { die "I DIED\n" };

exit main;
__END__

=head1 NAME

test_exception - exercise gimp-perl filter testing exceptions

=head1 SYNOPSIS

<Image>/Filters/Languages/_Perl/_Test/Exception

=head1 DESCRIPTION

exercise gimp-perl filter testing exceptions

=head1 AUTHOR

boilerplate id

=head1 DATE

20140310

=head1 LICENSE

boilerplate id
