#!/usr/local/bin/perl -w

use strict;
use Gimp;
use Gimp::Fu;
#BEGIN { $Gimp::verbose = 1; }
#Gimp::set_trace(TRACE_ALL);

sub boilerplate_params {
  my ($testing, $menuloc, $imagetypes) = @_;
  (
    ("exercise gimp-perl filter testing $testing") x 2,
    ("boilerplate id") x 2,
    "20140310",
    N_$menuloc,
    ($imagetypes // "*"),
  );
}

&register(
  "test_exception",
  boilerplate_params(
    'exceptions',
    '<Image>/Filters/Languages/_Perl/_Test/Exception', '',
  ),
  [],
  sub { die "I DIED\n" }
);

exit main;
