#!/usr/bin/perl

use strict;
#BEGIN { $Gimp::verbose = 1; }
use Gimp qw(__ N_);
use Gimp::Net ();

N_"/Xtns/Perl"; # workaround for i18n weirdnesses

Gimp::set_trace(\$Gimp::Net::trace_res);
Gimp::ignore_functions(qw(gimp_progress_init gimp_progress_update));

Gimp::register_callback extension_perl_server => \&Gimp::Net::extension_perl_server;

Gimp::on_query {
   Gimp->install_procedure("extension_perl_server", "Start the Gimp-Perl Server",
                           "This is the server for plug-ins written using the Gimp::Net module",
                           "Marc Lehmann <pcg\@goof.com>", "Marc Lehmann", "1999-12-02",
                          # N_"<Toolbox>/Xtns/Perl/Server", undef, &Gimp::EXTENSION,
                           N_"<Toolbox>/Xtns/Perl/Server", undef, &Gimp::PLUGIN,
                           [
                            [&Gimp::PDB_INT32, "run_mode", "Interactive, [non-interactive]"],
                            [&Gimp::PDB_INT32, "flags", "internal flags (must be 0)"],
                            [&Gimp::PDB_INT32, "extra", "multi-purpose ;)"],
                            [&Gimp::PDB_INT32, "verbose", "Gimp verbose var"],
                           ],[]);

   Gimp->install_procedure("gimp_procedural_db_constant_register", "Register a plug-in specific integer constant",
                           "Plug-ins should register their custom constants using this function, so".
                           "other plug-ins (notably script-languages) can access these using symbolic names",
                           "Marc Lehmann <pcg\@goof.com>", "Marc Lehmann", "1999-07-07",
                         #  undef, undef, &Gimp::EXTENSION,
                           undef, undef, &Gimp::PLUGIN,
                           [
                            [&Gimp::PDB_STRING, "procedure", "The name of the function that uses this constant"],
                            [&Gimp::PDB_STRING, "arg_num", "The name of the argument that this constant is used for"],
                            [&Gimp::PDB_STRING, "constant_name", "The name of the constant, should be all-uppercase"],
                            [&Gimp::PDB_INT32,  "constant_value", "The (integer) value for this constant"],
                           ],[]);
   Gimp->install_procedure("gimp_procedural_db_set_default", "Set the default value for a plug-in argument",
                           "Plug-ins should register default values for their arguments",
                           "Marc Lehmann <pcg\@goof.com>", "Marc Lehmann", "1999-07-07",
                         #  undef, undef, &Gimp::EXTENSION,
                           undef, undef, &Gimp::PLUGIN,
                           [
                            [&Gimp::PDB_STRING, "procedure", "The name of the function that uses this constant"],
                            [&Gimp::PDB_STRING, "arg_num", "The name of the argument that this constant is used for"],
                            [&Gimp::PDB_INT32,  "default_value", "The default value for this constant"],
                           ],[]);
};

exit Gimp::main;
