#!/usr/bin/perl -w

# Use gaussian blur and levels to round selection corners

use Gimp qw(:auto __ N_);
use Gimp::Fu;
use Gimp::Util;

podregister {
  $image->undo_group_start;
  my $channel = gimp_selection_save($image);
  gimp_selection_none($image);
  plug_in_gauss_iir($image, $channel, $round, 1, 1);
  gimp_levels($channel, 0, 123, 133, 1.0, 0, 255);
  $image->select_item(CHANNEL_OP_REPLACE, $channel);
  gimp_image_remove_channel($image, $channel);
  # gimp_item_delete($channel);
  $image->undo_group_end;
  ();
};

exit main;
__END__

=head1 NAME

round_sel - Rounds a selection.

=head1 SYNOPSIS

<Image>/Select/Round...

=head1 DESCRIPTION

Rounds a selection.

=head1 PARAMETERS

 [PF_SPINNER, "round", "How much to round, in pixels", 16, [1,1000,1]],

=head1 IMAGE TYPES

*

=head1 AUTHOR

Uri Zarfaty <udz20@cam.ac.uk>

=head1 DATE

1999-03-25

=head1 LICENSE

Copyright.
