#!/usr/bin/perl

eval 'exec /usr/bin/perl  -S $0 ${1+"$@"}'
    if 0; # not running under some shell

use Gimp qw(:auto __ N_);
use Gimp::Fu;

N_"/Xtns/Render"; # dummy translation for i18n bugs

sub stamps {
	my ($size, $hole, $paper, $diameter, $gap) = @_;

	gimp_context_set_background($paper);
	$img = gimp_image_new($size, $size, RGB);
	$layer = gimp_layer_new($img, $size, $size, RGB_IMAGE, "Layer 1", 100, NORMAL_MODE);
	gimp_image_insert_layer($layer, 0, -1);
	gimp_context_set_background($hole);
	$layer->gimp_edit_fill(BACKGROUND_FILL);
	gimp_selection_none($img);

	my $ncircles = int(($size + $gap) / ($diameter + $gap));
	$x = 0;
	for ($i=0; $i<$ncircles; $i++) {
			gimp_image_select_ellipse($img,
					CHANNEL_OP_ADD, $x, 0,
					$diameter, $diameter,
					);
			gimp_image_select_ellipse($img,
					CHANNEL_OP_ADD, 0, $x,
					$diameter, $diameter,
					);
			$x = $x + $diameter + $gap;
	}
	gimp_context_set_background($paper);
	gimp_edit_fill($layer, BACKGROUND_FILL);
	gimp_selection_none($img);

# here, at last, comes the clever part! :-)
	$layer->offset(1, 0, -($diameter / 2), -($diameter / 2));
	gimp_display_new($img);
	return $img;
}

register	"stamps",
		"Creates a rectangular image with stamp-like perforations.",
		"Default values are not bad!",
		"Claes G Lindblad <claesg\@algonet.se>",
		"Claes G Lindblad <claesg\@algonet.se>",
		"990314",
		N_"<Image>/File/Create/Logos/Stamps...",
		undef,
	[
	[PF_INT32, "size", "img size", 90],
	[PF_COLOR, "paper", "paper color", [255, 255, 255]],
	[PF_COLOR, "hole", "hole color", [0, 0, 0]],
	[PF_INT32, "diameter", "diameter", 10],
	[PF_INT32, "gap", "gap", 5]
	],
	\&stamps;

exit main;

=head1 LICENSE

Copyright Claes G. Lindblad.
Distributed under the terms of the GNU public license, v2 or higher.

=cut
