#!/usr/bin/perl

eval 'exec /usr/bin/perl  -S $0 ${1+"$@"}'
    if 0; # not running under some shell

# sent to me by Seth Burgess <sjburges@gimp.org>
# small changes my Marc Lehmann <pcg@goof.com>
# 2014/03/17 ported to GIMP 2.8.10 by Ed J - ported to Scheme (see end
#   for Scheme script), changes back-ported to perl but not tested
#   - I think the fill with the foreground colour should be background
#     since that's the colour expressly set, but didn't touch
#   - adjusted the maths so inputs are in degrees

# There's corruption on the edges of this in smear mode.  Yuck.

use Gimp qw(:auto N_ __);
use Gimp::Fu;

#Gimp::set_trace(TRACE_CALL);

sub windify {
	my ($img, $drawable, $angle, $density, $distance, $wrap) = @_;
	gimp_context_push();
	my $xsize = gimp_drawable_width($drawable);
	my $ysize = gimp_drawable_height($drawable);

	my $out = gimp_image_new($xsize,$ysize,0);
        #gimp_display_new($out); # if do this, image_delete will fail
	gimp_context_set_background([128,128,128]);
	my $windlayer = gimp_layer_new($out,$xsize,$ysize,RGB_IMAGE,"Windlayer",100,NORMAL_MODE);
	gimp_drawable_fill($windlayer, 0);
	gimp_image_insert_layer($out,$windlayer,0,0);
	my $windlayercopy = gimp_layer_copy($windlayer, 1);
	gimp_image_insert_layer($out,$windlayercopy,0,0);
	plug_in_noisify($out,$windlayercopy,0,$density/255,
                                                $density/255,
                                                $density/255,1);

	plug_in_mblur($out,$windlayercopy,
                     0,  #0=linear
                     15, #length
                     $angle,
                     gimp_drawable_width($windlayercopy)/2,
                     gimp_drawable_height($windlayercopy)/2
                     );
	gimp_layer_set_mode($windlayercopy, 10); # Lighten Only
	gimp_image_merge_visible_layers($out,0);

# many thanks to Dov for this suggestion as a workaround to the
# gimp_image_merge_visible_layers bug

	my $newlay = gimp_image_get_active_layer ($out);
        my $xmult = cos(3.14159*$angle/180);
        my $ymult = sin(3.14159*$angle/180);

	plug_in_displace($img,$drawable,-$distance*$xmult,
                                          $distance*$ymult,
					  1,1, $newlay,$newlay, $wrap);
        gimp_drawable_offset($drawable,1,0,$distance*$xmult,-$distance*$ymult);
	gimp_image_remove_layer($out,$newlay);
	gimp_image_delete ($out);
	gimp_displays_flush();
        gimp_context_pop();

	undef;
	}

register
	"windify",
	"Add wind to an image",
	"Blow your image all over :)",
	"Seth Burgess",
	"Seth Burgess <sjburges\@gimp.org>",
	"1998-09-14",
	N_"<Image>/Filters/Distorts/Windify...",
	"*",
	[
	 [PF_INT32, "angle", "Wind Angle in degrees, 0 is right, increases anticlockwise", 120],
	 [PF_INT32, "density", "How Much Is Blown",80],
	 [PF_VALUE, "distance", "How Far It's Blown",30],
	 [PF_TOGGLE, "wrap", "Smear on Edges (or Wrap)",1]
	],
	\&windify;

exit main;

=head1 LICENSE

Copyright Seth Burgess.
Distributed under the same terms as Gimp-Perl.

=cut

__END__
; scheme version of above
(define (script-fu-windify img drawable angle density distance wrap)
  (let* (
        (xsize (car (gimp-drawable-width drawable)))
        (ysize (car (gimp-drawable-height drawable)))
        (out 0)
        (windlayer 0)
        (windlayercopy 0)
        (scaledensity (/ density 255))
        (newlay 0)
        (xmult (cos (* (/ angle 180) 3.14159)))
        (ymult (sin (* (/ angle 180) 3.14159)))
        )
    (gimp-context-push)
    (set! out (car (gimp-image-new xsize ysize RGB)))
;    (gimp-display-new out)
    (gimp-context-set-background '(128 128 128))
    (set! windlayer (car (gimp-layer-new out xsize ysize RGB-IMAGE '"Windlayer" 100 NORMAL-MODE)))
    (gimp-drawable-fill windlayer 0)
    (gimp-image-add-layer out windlayer 0)
    (set! windlayercopy (car (gimp-layer-copy windlayer 1)))
    (gimp-image-add-layer out windlayercopy 0)
    (plug-in-noisify 1 out windlayercopy 0 scaledensity scaledensity scaledensity 1)
    (plug-in-mblur 1 out windlayercopy 0 15 angle (/ xsize 2) (/ ysize 2))
    (gimp-layer-set-mode windlayercopy 10) ; Lighten Only
    (gimp-image-merge-visible-layers out 0)
    (set! newlay (car (gimp-image-get-active-layer out)))
    (plug-in-displace 1 img drawable (* distance xmult) (* distance ymult) 1 1 newlay newlay wrap)
    (gimp-drawable-offset drawable 1 0 (* distance xmult) (* -1 distance ymult))
    (gimp-image-remove-layer out newlay)
    (gimp-image-delete out)
;(gimp-message (number->string xsize))
    (gimp-displays-flush)
    (gimp-context-pop)
  )
)

(script-fu-register "script-fu-windify"
  "Windify (GP)..."
  "Add wind to an image"
  "Seth Burgess"
  "Seth Burgess <sjburges@gimp.org>"
  "1998-09-14"
  ""
  SF-IMAGE "Image" 0
  SF-DRAWABLE "Drawable" 0
  SF-ADJUSTMENT "Wind Angle in degrees, 0 is right, increases anticlockwise" '(120 1 1000 1 10 0 1)
  SF-ADJUSTMENT "How Much Is Blown" '(80 1 1000 1 10 0 1)
  SF-ADJUSTMENT "How Far It's Blown"  '(30 1 1000 1 10 0 1)
  SF-TOGGLE "Smear on Edges (or Wrap)" TRUE
)

(script-fu-menu-register "script-fu-windify" "<Image>/Filters")
